canonical: https://www.medizininformatik-initiative.de/fhir/ext/modul-lungenfunktion
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: mii-ig-lungenfunktion
name: MII_IG_Lungenfunktion
status: active
version: 2026.0.0
packageId: de.medizininformatikinitiative.kerndatensatz.lungenfunktion
copyrightYear: 2024+
releaseLabel: ci-build
publisher:
  name: Medizininformatik Initiative
  url: https://www.medizininformatik-initiative.de/
dependencies:
  de.medizininformatikinitiative.kerndatensatz.meta: 2025.0.0
  hl7.fhir.r4.core: 4.0.1



# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
