@startuml UML Modul Lungenfunktion
skinparam Linetype ortho
skinparam Nodesep 150
skinparam Ranksep 80
skinparam legendBackgroundColor #white

class Lungenfunktionstestung{
    kann enthalten:
    Referenz(Bodyplethysmographie)
    Referenz(Spirometrie)
    Referenz(Blutgase_ateriell)
    Referenz(Diffusion_single_breath)
    Referenz(Provationstestung)
    Referenz(Vitalparameter_Körpermaße)
    Referenz(Risikofaktoren)
    Referenz(Demografische Daten)
}

class Bodyplethysmographie <<DiagnosticReport and Procedure>>{
    {field} Spirometrie 0..1 Reference(DiagnosticReport)
    R_tot
    sR_tot
    sR_eff
    sG_tot
    FRCpleth
    ERV
    RV
    TLC
    RV/TLC
    TGV
    ITGV
}
class Spirometrie <<DiagnosticReport and Procedure>>{
    BF
    FVC
    SVC
    FIVC
    IVC
    IC
    {field} FEV 0..* Reference(Observation)
    FIV
    TV
    ERV
    IRV
    MVV
    PEFR
    PIFR
    FEF
    FIF
    MEP
    MIP
    SNIP
    FEV1/FVC_Ratio
    FEV1/SVC_Ratio
    FEV1/FEV6_Ratio
    FEV1/IVC_Ratio
}

class Diffusion_single_breath <<DiagnosticReport and Procedure>> {
    TLCO_SB
    KCO_SB
    VA_SB
    {field} Hb(Referenz, zur Interpretation wichtig)
    DLCOcSB
    KCOcSb
    TA
    VIN_SB
    TLC_SB
    FRC_SB
    ERV_SB
    RV_SB
    RV%TLC_SB
}

class Blutgase_ateriell <<Observation from KDS_Labor>> {
    pHa
    PaCO2
    PaO2
    SaO2
    Hb
    CoHb
    STB
    BE
    Glu
    Lac
}

class Provokationstestung <<DiagnosticReport and Procedure>> {
    Sequenznummer
    Durchführungstyp
    Substanz
    Kumulierte Dosis
    Dosis
    FEV 1 Wert
    Threshold Dose Wert erreicht
}

class Vitalparameter_Körpermaße <<Observation from ISIK/ICU>>

class DemografischeDaten <<plus Modul Patient>> {
    Ethnie
    Biologisches Geschlecht
}

class Risikofaktoren <<Observation>> {
    Raucher
    Allergie
}

Lungenfunktionstestung -d- Bodyplethysmographie
Lungenfunktionstestung -u- Spirometrie
Lungenfunktionstestung -u- Diffusion_single_breath
Lungenfunktionstestung -u- Blutgase_ateriell
Lungenfunktionstestung -d- Provokationstestung
Lungenfunktionstestung -r- DemografischeDaten
Lungenfunktionstestung -l- Vitalparameter_Körpermaße
Lungenfunktionstestung -d- Risikofaktoren
@enduml