//EXAMPLE LM
//Head
Logical: MII_LM_Lungenfunktion
Parent: Element
Id: mii-lm-lungenfunktion
Title: "MII LM Lungenfunktion"
Description: "MII LogicalModel Modul Lungenfunktion"
//Translation
* insert Translation(^name, en-US, MII_LM_Lungenfunktion)
* insert Translation(^title, en-US, MII LM Lungenfunktion)
* insert Translation(^description, en-US, MII LogicalModel Module Lungenfunktion)
//Meta
* insert Publisher
* insert PR_CS_VS_Version
* insert LicenseCodeableCCBY40
* insert PR_CS_VS_Date
* ^url = "https://www.medizininformatik-initiative.de/fhir/ext/modul-lungenfunktion/StructureDefinition/LogicalModel/Lungenfunktion"
* . ^short = "Das Erweiterungsmodul Lungenfunktion enthält Datenelemente zur Dokumentation von Lungenfunktionsuntersuchungen (Spirometrie, Bodyplethysmographie, Diffusionskapazität, Provokationstestung) und zugehörigen Befundberichten."
//LM
* Lungenfunktionsprozedur 0..1 BackboneElement "Lungenfunktionsprozedur" "Generische Prozedur einer Lungenfunktionmessung. Hier soll das MII KDS-Profil Prozedur verwendet werden."
  * Status 1..1 http://hl7.org/fhir/StructureDefinition/Coding "Status" "Status der Lugenfunktionsmessung"
  * Kategorie 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Kategorie" "Kategoriesierung der Lungenfunktionmessung nach SNOMET-CT: 23426006 |Measurement of respiratory function (procedure)|"
  * Code 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Code" "Code für spezifische Lungenfunktionsmessung"
  * Person 1..1 Reference(Patient) "Person" "Person, auf die sich die Lungenfunktionsmessung bezieht. Hier soll das MII KDS-Profil Person verwendet werden."
  * Befundungszeit 1..1 http://hl7.org/fhir/StructureDefinition/dateTime "Befundungszeit" "Befundungszeitpunkt der Lungenfunktionsmessung."
  * Durchfuehrungserfolg 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Durchführungserfolg" "Durchführungserfolg der Lungenfunktionsmessung: Erfolgreich | nicht Erfolgreich | teilweise Erfolgreich"
  * Bericht 0..* Reference(DiagnosticReport) "Bericht" "Referenz auf den Bericht"
* Lungenfunktionsbefund 0..1 BackboneElement "Lungenfunktionsbefund" "Generischer Befund einer Lungenfunktionsprozedur"
  * Status 1..1 http://hl7.org/fhir/StructureDefinition/Coding "Status" "Status des Befundberichts."
  * Kategorie 1..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Kategorie" "Kategorisierung des Befunds zur Lungenfunktion nach SNOMED-CT: 720449003 |Pulmonary function report (record artifact)|"
  * Code 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Code" "Code für den spezifischen Lungenfunktionsbericht."
  * Person 1..1 Reference(Patient) "Personen-Identifikation" "Die Person, für die der Lungenfunktionsbericht erstellt wurde. Hier sollte das MII KDS-Modul Person referenziert werden"
  * Fall 0..1 Reference(Encounter) "Fall-Referenz" "Referenz über Fall auf den Versorgungsstellenkontakt. Hier soll das MII KDS-Modul Fall referenziert werden"
  * Zeitpunkt 0..1 http://hl7.org/fhir/StructureDefinition/dateTime "Klinisch relevanter Zeitpunkt" "Klinisch relevanter Zeitpunkt, auf den sich der Bericht bezieht."
  * Periode 0..1 http://hl7.org/fhir/StructureDefinition/Period "Klinisch relevante Periode" "Klinisch relevante Periode, auf die sich der Bericht bezieht."
  * ZeitpunktErstellung 0..1 http://hl7.org/fhir/StructureDefinition/dateTime "Zeitpunkt der Erstellung" "Zeitpunkt der Erstellung des Berichts."
  * Beobachtung 0..* Reference(Observation) "Beobachtung" "Referenz auf die Lungenfunktionsmesswerte."
  * InterpretationBeobachtung 0..1 http://hl7.org/fhir/StructureDefinition/markdown "Interpretation" "Freitextinterpretation der Lungenfunktionsmessung."
  * StrukturierteInterpretation 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Strukturierte Interpretation" "Strukturierte Interpretation der Lungenfunktionsmessung."
  * Dokumentenanhang 0..* http://hl7.org/fhir/StructureDefinition/Attachment "Dokumentenanhang" "Anhang der Dokumente und Bilder."
* Lungenfunktionsmesswerte 0..1 BackboneElement "Lungenfunktionsmesswerte" "Generische Messwerte einer Lungenfunktionsprozedur"
  * Prozedur 0..1 Reference(Procedure) "Prozedur" "Prozedur der Lungenfunktionsmessung"
  * Status 1..1 http://hl7.org/fhir/StructureDefinition/Coding "Status" "Status des Befundberichts."
  * Kategorie 1..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Kategorie" "Kategorisierung des Messwerts zur Lungenfunktion."
  * Code 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Code" "Code für den spezifischen Lungenfunktionsbericht."
  * Person 1..1 Reference(Patient) "Personen-Identifikation" "Die Person, für die der Lungenfunktionsbericht erstellt wurde. Hier sollte das MII KDS-Modul Person referenziert werden"
  * Dokumentationszeitpunkt 0..1 http://hl7.org/fhir/StructureDefinition/dateTime "Dokumentationszeitpunkt " "Zeitpunkt an dem der Messwert dokumentiert wurde."
  * Messergebnis 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Messergebnis" "Messergebnis eines Lungenfunktionsmesswert"
  * Interpretation 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Interpretation" "Interpretation der Messergebnisse im Bezug zum Referenzintervall."
  * Messverfahren 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Messverfahren" "Verfahren, wie der Messwert aufgenommen wurden."
  * Referenzintervall 0..1 BackboneElement "Referenzintervall" "Intervall zur Auswertung des Messwertes"
    * UntererReferenzwert 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Unterer Referenzwert" "Unter Referenzwert, oder auch LLN"
    * ObererReferenzwert 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Oberer Referenzwert" "Oberer Refernzwert, oder auch ULN"
    * Referenzalter 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Referenzalter" "Alter, auf welchen sich das Referenzintervall bezieht."
  * WeitereMesswerte 0..* Reference(Observation) "WeitereMesswert" "Weitere Messwerte, die mit diesem zusammengehören."
  * Bezugsmesswerte 0..* Reference(Observation) "Bezugsmesswerte" "Messwerte, aus welche dieser berechnet wurde."
  * Bewertungsmesswerte 0..* BackboneElement "Bewertungsmesswerte" "Messwerte, die zur Bewertung dieses Messwerts dient."
    * VorhergesagterMesswert 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Vorhergesagter Messwert" "Messwert, der personenbezogen vorhergesagt wird."
    * VerhaeltnisZurVorhersage 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Verhältnis zur Vorhersage" "Verhältnis von Messwert zum vorhergesagtem Messwert."
    * zScore 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "z-Score" "z-Score zur Bewertung des Messwerts"
* Umgebungsvariablen 0..1 BackboneElement "Umgebungsvariablen" "Umgebungsvariablen zur Beschreibung des Patientenumfeld"
  * Umgebung 0..1 BackboneElement "Umgebung" "Umgebung in der der Messwert aufgenommen wurde"
    * Standorttyp 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Standorttyp" "Typ der Umgebung des Patienten"
    * Standortform 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Standortform" "Standortform der Umgebung, zur Dokumentation von Innen oder Außen"
  * Luftfeuchtigkeit 0..1 BackboneElement "Luftfeuchtigkeit" "relative Luftfeuchtigkeit in der Patientenumgebung"
    * Status 1..1 http://hl7.org/fhir/StructureDefinition/Coding "Status" "Status des Befundberichts."
    * Kategorie 1..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Kategorie" "Kategorisierung des Messwerts zur Lungenfunktion."
    * Code 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Code" "Code für den spezifischen Lungenfunktionsbericht."
    * Person 1..1 Reference(Patient) "Personen-Identifikation" "Die Person, für die der Lungenfunktionsbericht erstellt wurde. Hier sollte das MII KDS-Modul Person referenziert werden"
    * Fokus 1..1 Reference(Location) "Fokus" "Fokus auf den Ort der Messung"
    * Dokumentationszeitpunkt 0..1 http://hl7.org/fhir/StructureDefinition/dateTime "Dokumentationszeitpunkt " "Zeitpunkt an dem der Messwert dokumentiert wurde."
    * Messergebnis 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Messergebnis" "Messergebnis eines Lungenfunktionsmesswert"
    * Interpretation 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Interpretation" "Interpretation der Messergebnisse im Bezug zum Referenzintervall."
  * Lufttemperatur 0..1 BackboneElement "Lufttemperatur" "Lufttemperatur in der Patientenumgebung"
    * Status 1..1 http://hl7.org/fhir/StructureDefinition/Coding "Status" "Status des Befundberichts."
    * Kategorie 1..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Kategorie" "Kategorisierung des Messwerts zur Lungenfunktion."
    * Code 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Code" "Code für den spezifischen Lungenfunktionsbericht."
    * Person 1..1 Reference(Patient) "Personen-Identifikation" "Die Person, für die der Lungenfunktionsbericht erstellt wurde. Hier sollte das MII KDS-Modul Person referenziert werden"
    * Fokus 1..1 Reference(Location) "Fokus" "Fokus auf den Ort der Messung"
    * Dokumentationszeitpunkt 0..1 http://hl7.org/fhir/StructureDefinition/dateTime "Dokumentationszeitpunkt " "Zeitpunkt an dem der Messwert dokumentiert wurde."
    * Messergebnis 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Messergebnis" "Messergebnis eines Lungenfunktionsmesswert"
    * Interpretation 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Interpretation" "Interpretation der Messergebnisse im Bezug zum Referenzintervall."
  * CO2Konzentration 0..1 BackboneElement "CO2 Konzentration" "CO2 Konzentration in der Patientenumgebung"
    * Status 1..1 http://hl7.org/fhir/StructureDefinition/Coding "Status" "Status des Befundberichts."
    * Kategorie 1..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Kategorie" "Kategorisierung des Messwerts zur Lungenfunktion."
    * Code 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Code" "Code für den spezifischen Lungenfunktionsbericht."
    * Person 1..1 Reference(Patient) "Personen-Identifikation" "Die Person, für die der Lungenfunktionsbericht erstellt wurde. Hier sollte das MII KDS-Modul Person referenziert werden"
    * Fokus 1..1 Reference(Location) "Fokus" "Fokus auf den Ort der Messung"
    * Dokumentationszeitpunkt 0..1 http://hl7.org/fhir/StructureDefinition/dateTime "Dokumentationszeitpunkt " "Zeitpunkt an dem der Messwert dokumentiert wurde."
    * Messergebnis 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Messergebnis" "Messergebnis eines Lungenfunktionsmesswert"
    * Interpretation 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Interpretation" "Interpretation der Messergebnisse im Bezug zum Referenzintervall."

//Mapping Profiles
Mapping: Lungenfunktion-LogicalModel
Id: FHIR
Title: "Bildgebung LogicalModel FHIR Mapping"
Source: MII_LM_Lungenfunktion
* Lungenfunktionsprozedur -> "Procedure"
  * Status -> "Procedure.status"
  * Kategorie -> "Procedure.category"
  * Code -> "Procedure.code"
  * Person -> "Procedure.subject"
  * Befundungszeit -> "Procedure.performedDateTime"
  * Durchfuehrungserfolg -> "Procedure.outcome"
  * Bericht -> "Procedure.report"
* Lungenfunktionsbefund -> "DiagnosticReport"
  * Status -> "DiagnosticReport.status"
  * Kategorie -> "DiagnosticReport.category"
  * Code -> "DiagnosticReport.code"
  * Person -> "DiagnosticReport.subject"
  * Fall -> "DiagnosticReport.encounter"
  * Zeitpunkt -> "DiagnosticReport.effectiveDateTime"
  * Periode -> "DiagnosticReport.effectivePeriod"
  * ZeitpunktErstellung -> "DiagnosticReport.issued"
  * Beobachtung -> "DiagnosticReport.result"
  * InterpretationBeobachtung -> "DiagnosticReport.conclusion"
  * StrukturierteInterpretation -> "DiagnosticReport.conclusionCode"
  * Dokumentenanhang -> "DiagnosticReport.presentedForm"
* Lungenfunktionsmesswerte -> "Observation"
  * Prozedur -> "Observation.partOf"
  * Status -> "Observation.status"
  * Kategorie -> "Observation.category"
  * Code -> "Observation.code"
  * Person -> "Observation.subject"
  * Dokumentationszeitpunkt -> "Observation.issued"
  * Messergebnis -> "Observation.value[x]"
  * Interpretation -> "Observation.interpretation"
  * Messverfahren -> "Observation.method"
  * Referenzintervall -> "Observation.referenceRange"
    * UntererReferenzwert -> "Observation.referenceRange.low"
    * ObererReferenzwert -> "Observation.referenceRange.high"
    * Referenzalter -> "Observation.referenceRange.age"
  * WeitereMesswerte -> "Observation.hasMember"
  * Bezugsmesswerte -> "Observation.derivedFrom"
  * Bewertungsmesswerte -> "Observation.component"
    * VorhergesagterMesswert -> "Observation.component[predicted]"
    * VerhaeltnisZurVorhersage -> "Observation.component[%predicted]"
    * zScore -> "Observation.component[z-score]"
* Umgebungsvariablen -> ""
  * Umgebung -> "Location"
    * Standorttyp -> "Location.type"
    * Standortform -> "Location.physicalType"
  * Luftfeuchtigkeit -> "Observation"
    * Status -> "Observation.status"
    * Kategorie -> "Observation.category"
    * Code -> "Observation.code"
    * Person -> "Observation.subject"
    * Fokus -> "Observation.focus"
    * Dokumentationszeitpunkt -> "Observation.issued"
    * Messergebnis -> "Observation.value[x]"
    * Interpretation -> "Observation.interpretation"
  * Lufttemperatur -> "Observation"
    * Status -> "Observation.status"
    * Kategorie -> "Observation.category"
    * Code -> "Observation.code"
    * Person -> "Observation.subject"
    * Fokus -> "Observation.focus"
    * Dokumentationszeitpunkt -> "Observation.issued"
    * Messergebnis -> "Observation.value[x]"
    * Interpretation -> "Observation.interpretation"
  * CO2Konzentration -> "Observation"
    * Status -> "Observation.status"
    * Kategorie -> "Observation.category"
    * Code -> "Observation.code"
    * Person -> "Observation.subject"
    * Fokus -> "Observation.focus"
    * Dokumentationszeitpunkt -> "Observation.issued"
    * Messergebnis -> "Observation.value[x]"
    * Interpretation -> "Observation.interpretation"
//Mapping KDS
/*Mapping: Lungenfunktion-LogicalModel-Profile
Id: KDS-Profile
Title: "Lungenfunktion LogicalModel KDS-Profile Mapping"
Source: MII_LM_Lungenfunktion
*/
